M48
; DRILL file {KiCad (7.0.0)} date Fri Nov 10 08:28:05 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-10T08:28:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X5.0Y140.0
X5.0Y5.0
X175.0Y140.0
X175.0Y5.0
T2
X22.1Y98.69
X22.1Y23.76
X37.34Y74.56
X65.28Y74.56
X70.36Y105.04
X70.36Y22.49
T0
M30
